CREATE DATABASE ${MYSQL_DATABASE}; 
GRANT ALL ON *.* TO ${MYSQL_USER}@localhost IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL ON *.* TO phpmyadmin@localhost IDENTIFIED BY '${MYSQL_PASSWORD}';
FLUSH PRIVILEGES

